
CREATE TABLE IF NOT EXISTS  colors(
 id integer primary key generated by default as identity,
 value varchar(100) not null
); 


create table if not exists status(
  id integer primary key generated by default as identity,
  name varchar(20) not null check (name <> ''),
  coloid integer references colors(id),
  projectid integer references  projects(id)
);

create table IF not  exists users(
 id integer primary key generated by default as identity,
 name varchar(250) not  null,
 lastname varchar(250),
 email varchar(100)
);

create table if not exists tasks(
id integer primary key generated by default as identity,
name text not null check (name <> ''),
enddate date,
projectid integer references projects(id),
statusid integer  references status(id),
owneruserid integer references users(id),
devuserid integer references users(id)
);


create table IF not  exists projectUsers(
 id integer primary key generated by default as identity,
 projectId integer not null references projects(id),
 userId integer not null references users(id)
);
